# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RE783o2PhIxpfG5ACtdA1gbcbtEd_R9z
"""

#PalmerPenguin.py
#T. Stewart-Rowe
#9/27/2026
#Introduces the Palmer Penguin species

#Constant Declaration
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

#Output the species name with introductory text
print("Introducing the Palmer Penguins: ")
print("\t"+ SP_CHINSTRAP + "!")
print("\t"+ SP_GENTOO + "!")
print("and last but not least...")
print("\t"+ SP_ADELIE + "!")

#Display the species count
print("There are a total of", TOTAL_SPECIES, "penguin species in this data set.")